// Version information - automatically synced from package.json during build
// DO NOT EDIT THIS FILE MANUALLY - it is generated by scripts/sync-version.js
export const APP_VERSION = '0.0.0';
export const APP_COMMIT = '9857564';
