#!/usr/bin/env node

/**
 * Script to sync version from package.json to src/app/version.ts
 * This ensures the footer always displays the correct version and git commit
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionTsPath = path.join(__dirname, '..', 'src', 'app', 'version.ts');

function getGitCommitHash() {
  // First, check if commit hash is provided via environment variable (e.g., from Docker build arg)
  if (process.env.GIT_COMMIT) {
    // Use short version if it's a full hash
    return process.env.GIT_COMMIT.substring(0, 7);
  }
  
  try {
    // Try to get the current commit hash (short version)
    const commitHash = execSync('git rev-parse --short HEAD', { encoding: 'utf8', stdio: 'pipe' }).trim();
    return commitHash;
  } catch (error) {
    // If git is not available or not in a git repo, return 'unknown'
    // This can happen during Docker builds or if git is not installed
    return 'unknown';
  }
}

try {
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  const version = packageJson.version;
  const commitHash = getGitCommitHash();

  const versionTsContent = `// Version information - automatically synced from package.json during build
// DO NOT EDIT THIS FILE MANUALLY - it is generated by scripts/sync-version.js
export const APP_VERSION = '${version}';
export const APP_COMMIT = '${commitHash}';
`;

  fs.writeFileSync(versionTsPath, versionTsContent, 'utf8');
  console.log(`✓ Synced version ${version} (commit: ${commitHash}) from package.json to version.ts`);
} catch (error) {
  console.error('Error syncing version:', error);
  process.exit(1);
}

